### ISSUE TITLE
Set up the database

### ISSUE THREAD

**Issue by EstherMuigai** [EstherMuigai/eventsbuddy#3]
Create all model classes with their relevant CRUD functions.
Naming convention for class-table-function:
1. Event - events - save_event
2. Admin - admins - save_admin
3. User - users - save_user
4.Question - questions - save_question
5. Response - responses -save_response

**Comment by GabrielOduori** [comment]
Added three classes to the model.

**Comment by GabrielOduori** [comment]
All model classes created and pushed to the branch feature/models.

**Comment by GabrielOduori** [comment]
Database creation and save methods all completed.  Initial migration done as required.  Tables coming up as expected. Here is a screenshot of the tables.

![EventsBuddy](https://user-images.githubusercontent.com/3750661/57015081-9b7ba800-6c1b-11e9-85a8-d6fb12beaef2.png)
